### ISSUE TITLE
Remove DNS Config again

### ISSUE THREAD

**Issue by ghost** [serlo/infrastructure-modules-kpi#2]
@inyono fixed the DNS issues in staging and prod envs. We can remove the DNS config in kpi-module again: 

`dns_config {
          nameservers = ["8.8.8.8"]
          option {
            name  = "ndots"
            value = 1
          }
        }`

**Comment by Lodifice** [comment]
Thanks, I've had problems with my local minikube, so there was no progress on my side.
I have removed the DNS config and now the module works locally.

I'd test on dev next, but dev is incompatible with the latest changes to some modules. I'll wait for it until your PR on dev is merged.

**Comment by inyono** [comment]
This got resolved in https://github.com/serlo/infrastructure-modules-kpi/commit/60082bcb9a144a7b82238ed5519963bb8ff3b147
