### ISSUE TITLE
Container for MFNF migration tool

### ISSUE THREAD

**Issue by Lodifice** [serlo/infrastructure-modules-kpi#9]
The MFNF migration project needs a website for monitoring the state of the migration.
The container is to be build from the Dockerfile in [this directory](https://github.com/serlo/mfnf-to-edtr-mapping/tree/main/mfnf2serlo).
Please create a pod hosting this container that is constantly running and accessible from the internet to serve a website.
The container features a cronjob that regenerates the contents every night.
An alternative would be to restart the container each night, as the contents are build at start as well.
Since updates to the image will be required, especially in the beginning, it would be nice if I had the rights to push a new image and rebuild the container.

- [x] Create a module
- [ ] Add action for updating the image based on version

**Comment by hugotiburtino** [comment]
It is deployed under https://mfnf.serlo.org/

At the time of writing, it spent more one hour with different CPU limits and it couldn't still parte the Axiomatische Mengenlehre (see https://github.com/serlo/mfnf-to-edtr-mapping/issues/1). 

![image](https://user-images.githubusercontent.com/45924645/213939805-62b62e6f-a5ce-4219-9627-bdfe1e158b8c.png)

I had to start the server manually.

It has now 950M cpu and let's see if it can do the job with it.

Any way we could optimize https://github.com/serlo/mediawiki-parser?
